ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "mapKey" TEXT NOT NULL DEFAULT 'forest';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "mapId" TEXT NOT NULL DEFAULT 'Z1';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "posX" DOUBLE PRECISION NOT NULL DEFAULT 500;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "posY" DOUBLE PRECISION NOT NULL DEFAULT 500;

